CREATE TABLE IF NOT EXISTS smart_lock_integrations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    credential_ciphertext LONGTEXT NOT NULL,
    credential_fingerprint VARCHAR(128) NULL,
    token_expires_at DATETIME NULL,
    connection_status VARCHAR(30) NOT NULL DEFAULT 'DISCONNECTED',
    last_test_at DATETIME NULL,
    last_sync_at DATETIME NULL,
    last_error TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_smart_lock_integrations_store_provider (store_id, provider),
    INDEX idx_smart_lock_integrations_store (store_id)
);

CREATE TABLE IF NOT EXISTS smart_lock_devices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    integration_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_lock_id VARCHAR(120) NOT NULL,
    lock_name VARCHAR(150) NOT NULL,
    device_type VARCHAR(80) NULL,
    auxiliary_device_id VARCHAR(120) NULL,
    battery INT NULL,
    lock_status VARCHAR(40) NULL,
    online BOOLEAN NULL,
    raw_data_json LONGTEXT NULL,
    last_synced_at DATETIME NULL,
    last_status_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_smart_lock_devices_store_provider_lock (store_id, provider, provider_lock_id),
    INDEX idx_smart_lock_devices_store_integration (store_id, integration_id),
    INDEX idx_smart_lock_devices_store_provider (store_id, provider)
);

CREATE TABLE IF NOT EXISTS smart_lock_room_bindings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    integration_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_lock_id VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    active_room_id BIGINT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN room_id ELSE NULL END) STORED,
    active_provider_lock_id VARCHAR(120) GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN provider_lock_id ELSE NULL END) STORED,
    created_by BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_smart_lock_bindings_active_room (store_id, active_room_id),
    UNIQUE KEY uk_smart_lock_bindings_active_provider_lock (store_id, provider, active_provider_lock_id),
    INDEX idx_smart_lock_bindings_store_room (store_id, room_id),
    INDEX idx_smart_lock_bindings_store_provider_lock (store_id, provider, provider_lock_id),
    INDEX idx_smart_lock_bindings_store_device (store_id, device_id),
    INDEX idx_smart_lock_bindings_store_integration (store_id, integration_id)
);

CREATE TABLE IF NOT EXISTS smart_lock_confirmations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    binding_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    reason VARCHAR(500) NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_smart_lock_confirmations_store_token (store_id, token_hash),
    INDEX idx_smart_lock_confirmations_store_room (store_id, room_id),
    INDEX idx_smart_lock_confirmations_store_binding (store_id, binding_id)
);

CREATE TABLE IF NOT EXISTS smart_lock_passcode_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    binding_id BIGINT NOT NULL,
    integration_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_lock_id VARCHAR(120) NOT NULL,
    provider_passcode_id VARCHAR(120) NULL,
    provider_task_id VARCHAR(120) NULL,
    passcode_name VARCHAR(120) NOT NULL,
    passcode_masked VARCHAR(40) NOT NULL,
    passcode_hash VARCHAR(128) NOT NULL,
    valid_from DATETIME NULL,
    valid_until DATETIME NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    last_error TEXT NULL,
    created_by BIGINT NOT NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_smart_lock_passcodes_store_room (store_id, room_id),
    INDEX idx_smart_lock_passcodes_store_binding (store_id, binding_id),
    INDEX idx_smart_lock_passcodes_store_provider_lock (store_id, provider, provider_lock_id)
);

CREATE TABLE IF NOT EXISTS smart_lock_tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    task_type VARCHAR(40) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    room_id BIGINT NULL,
    binding_id BIGINT NULL,
    passcode_record_id BIGINT NULL,
    confirmation_id BIGINT NULL,
    provider_task_id VARCHAR(120) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    idempotency_key VARCHAR(120) NULL,
    request_hash VARCHAR(128) NULL,
    result_message TEXT NULL,
    error_message TEXT NULL,
    reason VARCHAR(500) NULL,
    created_by BIGINT NOT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_smart_lock_tasks_store_idempotency (store_id, idempotency_key),
    INDEX idx_smart_lock_tasks_store_room (store_id, room_id),
    INDEX idx_smart_lock_tasks_store_binding (store_id, binding_id),
    INDEX idx_smart_lock_tasks_store_provider_task (store_id, provider_task_id),
    INDEX idx_smart_lock_tasks_store_passcode (store_id, passcode_record_id)
);
