CREATE TABLE IF NOT EXISTS channel_mapping_price_settings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    ota_integration_id BIGINT NULL,
    channel_code VARCHAR(50) NOT NULL,
    su_channel_id VARCHAR(20) NOT NULL,
    su_property_id VARCHAR(200) NOT NULL,
    channel_hotel_id VARCHAR(100) NULL,
    mapping_key VARCHAR(700) NOT NULL,
    row_key VARCHAR(1000) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    mapping_key_version VARCHAR(20) NOT NULL DEFAULT 'v1',
    room_id VARCHAR(100) NULL,
    rate_id VARCHAR(100) NULL,
    channel_room_id VARCHAR(100) NULL,
    channel_rate_id VARCHAR(100) NULL,
    listing_id VARCHAR(100) NULL,
    applicable_no_of_guest VARCHAR(50) NULL,
    occupancy VARCHAR(50) NULL,
    multiplier DECIMAL(12, 6) NULL,
    surcharge DECIMAL(12, 2) NULL,
    sync_status VARCHAR(32) NOT NULL DEFAULT 'UNSYNCED',
    last_error TEXT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_operation_id VARCHAR(64) NULL,
    last_batch_id VARCHAR(64) NULL,
    last_attempted_at DATETIME NULL,
    last_synced_at DATETIME NULL,
    last_failed_at DATETIME NULL,
    last_seen_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_channel_mapping_price_current (store_id, channel_id, mapping_key),
    KEY idx_channel_mapping_price_row_key (store_id, channel_id, row_key),
    KEY idx_channel_mapping_price_status (store_id, channel_id, sync_status),
    KEY idx_channel_mapping_price_operation (store_id, last_operation_id),
    KEY idx_channel_mapping_price_batch (store_id, last_batch_id),
    CONSTRAINT fk_channel_mapping_price_channel
        FOREIGN KEY (channel_id) REFERENCES channels (id)
);
