CREATE TABLE internal_tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    status VARCHAR(20) NOT NULL,
    assignee_user_id BIGINT NULL,
    assignee_name_snapshot VARCHAR(100) NULL,
    created_by_user_id BIGINT NOT NULL,
    created_by_name_snapshot VARCHAR(100) NOT NULL,
    completed_by_user_id BIGINT NULL,
    completed_by_name_snapshot VARCHAR(100) NULL,
    completed_at DATETIME NULL,
    archived_at DATETIME NULL,
    archived_by_user_id BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_internal_tasks_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_internal_tasks_assignee FOREIGN KEY (assignee_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_internal_tasks_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_internal_tasks_completed_by FOREIGN KEY (completed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_internal_tasks_archived_by FOREIGN KEY (archived_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_internal_tasks_mine_active (store_id, assignee_user_id, archived_at, status, created_at),
    INDEX idx_internal_tasks_mine_completed (store_id, assignee_user_id, archived_at, status, completed_at),
    INDEX idx_internal_tasks_managed_active (store_id, archived_at, status, created_at)
);
