CREATE TABLE managed_operation_settings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    property_name VARCHAR(200) NOT NULL DEFAULT '',
    management_fee_rate DECIMAL(8,6) NOT NULL DEFAULT 0.100000,
    tax_rate DECIMAL(8,6) NOT NULL DEFAULT 0.100000,
    cleaning_fee_gross DECIMAL(14,2) NOT NULL DEFAULT 8000.00,
    registration_fee_net DECIMAL(14,2) NOT NULL DEFAULT 2000.00,
    owner_company_name VARCHAR(200) NOT NULL DEFAULT '',
    owner_contact_name VARCHAR(100) NOT NULL DEFAULT '',
    owner_postal_code VARCHAR(30) NOT NULL DEFAULT '',
    owner_address VARCHAR(500) NOT NULL DEFAULT '',
    issuer_company_name VARCHAR(200) NOT NULL DEFAULT '',
    issuer_postal_code VARCHAR(30) NOT NULL DEFAULT '',
    issuer_address VARCHAR(500) NOT NULL DEFAULT '',
    issuer_registration_number VARCHAR(100) NOT NULL DEFAULT '',
    issuer_phone VARCHAR(50) NOT NULL DEFAULT '',
    issuer_email VARCHAR(200) NOT NULL DEFAULT '',
    bank_name VARCHAR(200) NOT NULL DEFAULT '',
    bank_branch VARCHAR(200) NOT NULL DEFAULT '',
    bank_account_type VARCHAR(50) NOT NULL DEFAULT '',
    bank_account_number VARCHAR(100) NOT NULL DEFAULT '',
    bank_account_holder VARCHAR(200) NOT NULL DEFAULT '',
    stamp_storage_key VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_managed_operation_settings_store (store_id),
    CONSTRAINT fk_managed_operation_settings_store FOREIGN KEY (store_id) REFERENCES stores(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE managed_operation_rooms (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    settings_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_managed_operation_room (store_id, settings_id, room_id),
    KEY idx_managed_operation_rooms_settings (settings_id),
    KEY idx_managed_operation_rooms_room (room_id),
    CONSTRAINT fk_managed_operation_rooms_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_managed_operation_rooms_settings FOREIGN KEY (settings_id) REFERENCES managed_operation_settings(id) ON DELETE CASCADE,
    CONSTRAINT fk_managed_operation_rooms_room FOREIGN KEY (room_id) REFERENCES rooms(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
