CREATE TABLE channel_reviews (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    reservation_id BIGINT NULL,
    association_status VARCHAR(20) NOT NULL,
    association_reason VARCHAR(500) NULL,
    pms_channel_code VARCHAR(30) NOT NULL,
    su_channel_id INT NOT NULL,
    hotel_id VARCHAR(50) NOT NULL,
    channel_property_id VARCHAR(150) NOT NULL,
    listing_id VARCHAR(255) NULL,
    channel_review_id VARCHAR(255) NOT NULL,
    channel_booking_id VARCHAR(255) NULL,
    review_type VARCHAR(50) NOT NULL,
    review_status VARCHAR(50) NULL,
    can_reply BOOLEAN NOT NULL DEFAULT FALSE,
    can_review_guest BOOLEAN NOT NULL DEFAULT FALSE,
    guest_name VARCHAR(200) NULL,
    property_name VARCHAR(255) NULL,
    check_in_date DATE NULL,
    check_out_date DATE NULL,
    review_title VARCHAR(500) NULL,
    review_text TEXT NULL,
    negative_review_text TEXT NULL,
    private_feedback TEXT NULL,
    overall_score DECIMAL(6,2) NULL,
    category_ratings_json LONGTEXT NULL,
    reply_text TEXT NULL,
    reply_at DATETIME(6) NULL,
    last_action_type VARCHAR(30) NULL,
    last_action_status VARCHAR(30) NULL,
    received_at DATETIME(6) NULL,
    last_synced_at DATETIME(6) NOT NULL,
    source_event_hash CHAR(64) NULL,
    su_ruid VARCHAR(100) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_channel_reviews_external (
        store_id,
        su_channel_id,
        channel_review_id,
        review_type
    ),
    KEY idx_channel_reviews_store_received (store_id, received_at, id),
    KEY idx_channel_reviews_store_reservation (store_id, reservation_id),
    KEY idx_channel_reviews_store_association (store_id, association_status),
    KEY idx_channel_reviews_store_action (store_id, last_action_status),
    CONSTRAINT fk_channel_reviews_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_channel_reviews_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE channel_review_actions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    store_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    operator_user_id BIGINT NOT NULL,
    response_message VARCHAR(1000) NULL,
    su_error_code VARCHAR(50) NULL,
    su_ruid VARCHAR(100) NULL,
    submitted_at DATETIME(6) NULL,
    confirmed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_channel_review_actions_idempotency (store_id, idempotency_key),
    KEY idx_channel_review_actions_review (store_id, review_id, created_at),
    KEY idx_channel_review_actions_pending (store_id, status, updated_at),
    CONSTRAINT fk_channel_review_actions_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_channel_review_actions_review FOREIGN KEY (review_id) REFERENCES channel_reviews(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
