import type { ReviewOrderRow } from './types'

export const mockReviewOrders: ReviewOrderRow[] = [
  {
    id: 'review-order-001',
    channel: 'Airbnb',
    orderNumber: 'PMS-20260528-001',
    channelOrderNumber: 'ABB-HM2QK9',
    guestName: 'Mika Tanaka',
    guestCount: 2,
    roomName: 'River View Studio 301',
    checkInDate: '2026-05-08',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 5,
    hostReviewDeadlineDays: 2,
    guestReview: {
      rating: 5,
      content: '房间很干净，入住说明清楚，位置也很方便。下次来还会考虑。',
      reviewedAt: '2026-05-13',
    },
  },
  {
    id: 'review-order-002',
    channel: 'Booking.com',
    orderNumber: 'PMS-20260527-004',
    channelOrderNumber: 'BKG-771452',
    guestName: 'Sigrid Hofmann Wazynski',
    guestCount: 2,
    roomName: '浅草401',
    checkInDate: '2026-05-09',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 4,
    hostReviewDeadlineDays: 3,
  },
  {
    id: 'review-order-003',
    channel: 'Booking.com',
    orderNumber: 'PMS-20260526-009',
    channelOrderNumber: 'BKG-770881',
    guestName: 'Walsh Richard',
    guestCount: 4,
    roomName: '67LEREVE Ikebukuro-4F',
    checkInDate: '2026-05-09',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 3,
    hostReviewDeadlineDays: 3,
  },
  {
    id: 'review-order-004',
    channel: 'Airbnb',
    orderNumber: 'PMS-20260525-003',
    channelOrderNumber: 'ABB-KY8PL3',
    guestName: 'Louis Mao',
    guestCount: 2,
    roomName: '神宮前4F',
    checkInDate: '2026-05-06',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 1,
    hostReviewDeadlineDays: 1,
    guestReview: {
      rating: 4,
      content: '房源位置很好，沟通顺畅。晚上街道略有噪音，但整体体验不错。',
      reviewedAt: '2026-05-13',
    },
  },
  {
    id: 'review-order-005',
    channel: 'Airbnb',
    orderNumber: 'PMS-20260524-010',
    channelOrderNumber: 'ABB-TD4M31',
    guestName: 'Steven Siebert',
    guestCount: 2,
    roomName: '67Hotel 三ノ輪 401',
    checkInDate: '2026-05-08',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 0,
    hostReviewDeadlineDays: 0,
    guestReview: {
      rating: 5,
      content: '房间舒适，适合短住。入住流程很顺利。',
      reviewedAt: '2026-05-12',
    },
    hostReview: {
      rating: 5,
      tags: ['clean', 'communicative', 'rules'],
      content: '客人沟通顺畅，退房后房间保持整洁，欢迎再次入住。',
      reviewedAt: '2026-05-13',
    },
  },
  {
    id: 'review-order-006',
    channel: 'Booking.com',
    orderNumber: 'PMS-20260523-006',
    channelOrderNumber: 'BKG-769502',
    guestName: 'Emma Wilson',
    guestCount: 1,
    roomName: 'APB Koenji 203',
    checkInDate: '2026-05-09',
    checkOutDate: '2026-05-12',
    orderStatus: 'CHECKED_OUT',
    guestReviewDeadlineDays: 2,
    hostReviewDeadlineDays: 0,
    hostReview: {
      rating: 4,
      tags: ['communicative', 'rules'],
      content: '沟通及时，遵守入住规则。退房时有少量垃圾未整理。',
      reviewedAt: '2026-05-12',
    },
  },
]
