export * as authApi from '@/api/auth'
export * as storeApi from '@/api/store'
export { default as homeApi } from '@/api/home'
export { default as statisticsApi } from '@/api/statistics'
export { default as notesApi } from '@/api/notes'
export { default as roomsApi } from '@/api/rooms'
export { default as ordersApi } from '@/api/orders'
export { default as channelsApi } from '@/api/channels'
export { default as settingsApi } from '@/api/settings'
export * as roomGroupApi from '@/api/roomGroup'
export * as sortConfigApi from '@/api/sortConfig'
export * as paymentMethodApi from '@/api/paymentMethod'
export * as noteCategoryApi from '@/api/noteCategory'
export * as publicRegistrationBookingApi from '@/api/publicRegistrationBooking'
export * as publicRegistrationApi from '@/api/publicRegistration'
export * as publicRoomStatusShareApi from '@/api/publicRoomStatusShare'
